AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 bucket
Parameters:
  MyBucketName:
    Type: String
    Default: azoutte-23123121
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: MyBucketName
#      AccessControl: PublicRead
